### ISSUE TITLE
[RESEARCH] bitbucket/pipeline: parallel mode  

### ISSUE THREAD

**Issue by developerasun** [developerasun/myDocumentBox-tool#34]
# topic : understanding parallel mode in bitbucket pipeline
## read this 

> When we built Bitbucket Pipelines, one of our goals was to make a tool that developers love. And if there’s one thing developers love, it is getting their builds finished more quickly. Last year, we added [dependency caching](https://bitbucket.org/blog/2017/06/27/faster-builds-dependency-caching/) and [detailed timing information](https://bitbucket.org/blog/2017/05/31/speed-builds-pipelines-command-duration/) to help speed up your builds.

> “Parallel steps in Pipelines has cut our CI time by two-thirds, saving our developers hours every week.” ? Shane Fast, Co-founder and CTO at Paper Interactive

```yml
image: node:9-alpine
 
pipelines:
  default:
    - step:
        name: Build
        script:
          - npm install
          - npm package
        artifacts:
          - dist/**  # copy these files to later steps
    - parallel:
        - step:
            name: Unit tests
            script:
              - npm run test/unit
        - step:
            name: Integration tests
            script:
              - npm run test/integration
        - step:
            name: Browser tests
            script:
              - npm run test/browserstack
    - step:
        name: Deploy to test
        deployment: test
        script:
          - npm run release --version $BITBUCKET_BUILD_NUMBER
          - npm run deploy/test
```

> It is primarily designed for large suites of automated tests, but can also be used for large compute tasks that can be parallelized.

> We’ve kept our existing limit of 10 steps per pipeline, as based on our data our customers don’t currently need more than this. We also expect running steps in parallel to have decreasing benefits beyond 10 steps, as the fixed overhead to start and stop the build starts becoming the limiting factor

## reference

- https://bitbucket.org/blog/speed-build-parallel-steps-pipelines
