### ISSUE TITLE
[RESEARCH] github/actions: environment variable

### ISSUE THREAD

**Issue by developerasun** [developerasun/myDocumentBox-tool#36]
# topic : understanding how to set custom environment variables in github actions
## read this 

> GitHub sets default environment variables for each GitHub Actions workflow run. You can also set custom environment variables in your workflow file.

> You can use environment variables to store information that you want to reference in your workflow. You reference environment variables within a workflow step or an action, and the variables are interpolated on the runner machine that runs your workflow. Commands that run in actions or workflow steps can create, read, and modify environment variables.

> You can set your own custom environment variables, you can use the default environment variables that GitHub sets automatically, and you can also use any other environment variables that are set in the working environment on the runner. Environment variables are case-sensitive.

> To set a custom environment variable, you must define it in the workflow file. The scope of a custom environment variable is limited to the element in which it is defined. You can define environment variables that are scoped for:

1. The entire workflow, by using [env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env) at the top level of the workflow file.
1. The contents of a job within a workflow, by using [jobs.<job_id>.env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenv).
1. A specific step within a job, by using [jobs.<job_id>.steps[*].env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv).

```yml
name: Greeting on variable day

on:
  workflow_dispatch

env: # top level env vars
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env: # job level env vars
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env: # step level env vars
          First_Name: Mona
```

## reference

- https://docs.github.com/en/actions/learn-github-actions/environment-variables
